export type RescheduleStatus = 'disponivel' | 'indisponivel' | 'expirado' | 'bloqueado';

// Função para contar documentos disponíveis por atendimento
export const getDocumentosDisponiveis = (atendimentoId: string): number => {
  const documentosPorAtendimento: { [key: string]: number } = {
    '1': 2,
    '2': 3,
    '3': 2,
    '5': 2,
    '7': 3,
    '8': 2,
    '11': 3,
    '12': 2,
  };
  return documentosPorAtendimento[atendimentoId] || 0;
};

export interface HistoricoItem {
  id: string;
  tipo: 'consulta' | 'exame' | 'cuidado';
  titulo: string;
  profissional: string;
  especialidade: string;
  data: string;
  hora: string;
  local: string;
  status: 'concluido' | 'cancelado' | 'reagendado';
  observacoes?: string;
  avatar: { uri: string };
  codigoAtendimento: string;
  duracao: string;
  comentarioProfissional: string;
  comentarioAdicional?: string;
  documentosDisponiveis: number;
  valorAtendimento: number;
  metodoPagamento: 'pix' | 'dinheiro' | 'cartao_credito';
  numeroCartao?: string; // últimos 4 dígitos
  parcelado: boolean;
  numeroParcelas?: number;
  valorParcela?: number;
  rescheduleStatus: RescheduleStatus;
}

export const mockHistoricoData: HistoricoItem[] = [
  {
    id: '1',
    tipo: 'consulta',
    titulo: 'Consulta Geral',
    profissional: 'Dr. João Silva',
    especialidade: 'Cardiologista',
    data: '15/10/2024',
    hora: '14:30',
    local: 'Hospital São Lucas',
    status: 'concluido',
    observacoes: 'Paciente apresentou melhora significativa nos sintomas.',
    avatar: { uri: 'https://api.dicebear.com/7.x/avataaars/png?seed=JoaoSilva&backgroundColor=FF6B6B&size=100' },
    codigoAtendimento: 'ATD-001',
    duracao: '45 min',
    comentarioProfissional: 'Paciente evoluiu bem com o tratamento prescrito. Recomendo manutenção da medicação atual.',
    comentarioAdicional: 'Paciente relatou redução significativa da pressão arterial.',
    documentosDisponiveis: getDocumentosDisponiveis('1'),
    valorAtendimento: 150.00,
    metodoPagamento: 'cartao_credito',
    numeroCartao: '4321',
    parcelado: true,
    numeroParcelas: 3,
    valorParcela: 50.00,
    rescheduleStatus: 'disponivel',
  },
  {
    id: '2',
    tipo: 'exame',
    titulo: 'Raio X',
    profissional: 'Dra. Maria Santos',
    especialidade: 'Clínica Geral',
    data: '12/10/2024',
    hora: '08:00',
    local: 'Laboratório Central',
    status: 'concluido',
    observacoes: 'Resultados dentro dos parâmetros normais.',
    avatar: { uri: 'https://api.dicebear.com/7.x/avataaars/png?seed=MariaSantos&backgroundColor=4576F2&size=100' },
    codigoAtendimento: 'ATD-002',
    duracao: '15 min',
    comentarioProfissional: 'Exame radiológico realizado sem intercorrências. Imagens de boa qualidade.',
    documentosDisponiveis: getDocumentosDisponiveis('2'),
    valorAtendimento: 80.00,
    metodoPagamento: 'pix',
    parcelado: false,
    rescheduleStatus: 'disponivel',
  },
  {
    id: '3',
    tipo: 'cuidado',
    titulo: 'Fisioterapia',
    profissional: 'Carlos Oliveira',
    especialidade: 'Fisioterapeuta',
    data: '20/10/2024',
    hora: '10:00',
    local: 'Clínica de Reabilitação',
    status: 'reagendado',
    observacoes: 'Tratamento para recuperação de lesão no joelho.',
    avatar: { uri: 'https://api.dicebear.com/7.x/avataaars/png?seed=CarlosOliveira&backgroundColor=4ECDC4&size=100' },
    codigoAtendimento: 'ATD-003',
    duracao: '60 min',
    comentarioProfissional: 'Sessão de fisioterapia realizada com exercícios de fortalecimento muscular.',
    comentarioAdicional: 'Paciente apresentou boa evolução motora.',
    documentosDisponiveis: getDocumentosDisponiveis('3'),
    valorAtendimento: 120.00,
    metodoPagamento: 'dinheiro',
    parcelado: false,
    rescheduleStatus: 'expirado',
  },
  {
    id: '4',
    tipo: 'consulta',
    titulo: 'Consulta Dermatológica',
    profissional: 'Dra. Ana Costa',
    especialidade: 'Dermatologista',
    data: '05/10/2024',
    hora: '16:00',
    local: 'Clínica Dermatológica',
    status: 'cancelado',
    observacoes: 'Consulta cancelada pelo paciente.',
    avatar: { uri: 'https://api.dicebear.com/7.x/avataaars/png?seed=AnaCosta&backgroundColor=FFE66D&size=100' },
    codigoAtendimento: 'ATD-004',
    duracao: '30 min',
    comentarioProfissional: 'Consulta cancelada conforme solicitado pelo paciente.',
    documentosDisponiveis: getDocumentosDisponiveis('4'),
    valorAtendimento: 100.00,
    metodoPagamento: 'cartao_credito',
    numeroCartao: '8765',
    parcelado: false,
    rescheduleStatus: 'indisponivel',
  },
  {
    id: '5',
    tipo: 'consulta',
    titulo: 'Consulta de Rotina',
    profissional: 'Dr. Carlos Mendes',
    especialidade: 'Clínico Geral',
    data: '15/10/2024',
    hora: '09:00',
    local: 'Centro Médico Central',
    status: 'concluido',
    observacoes: 'Check-up anual realizado com sucesso.',
    avatar: { uri: 'https://api.dicebear.com/7.x/avataaars/png?seed=CarlosMendes&backgroundColor=74B9FF&size=100' },
    codigoAtendimento: 'ATD-005',
    duracao: '40 min',
    comentarioProfissional: 'Exame físico completo realizado. Paciente em boas condições gerais.',
    comentarioAdicional: 'Pressão arterial dentro dos parâmetros normais.',
    documentosDisponiveis: getDocumentosDisponiveis('5'),
    valorAtendimento: 200.00,
    metodoPagamento: 'cartao_credito',
    numeroCartao: '1234',
    parcelado: true,
    numeroParcelas: 2,
    valorParcela: 100.00,
    rescheduleStatus: 'disponivel',
  },
  {
    id: '6',
    tipo: 'exame',
    titulo: 'Hemograma Completo',
    profissional: 'Dra. Sofia Lima',
    especialidade: 'Hematologista',
    data: '15/10/2024',
    hora: '11:30',
    local: 'Laboratório São José',
    status: 'concluido',
    observacoes: 'Exames de sangue realizados. Resultados normais.',
    avatar: { uri: 'https://api.dicebear.com/7.x/avataaars/png?seed=SofiaLima&backgroundColor=A29BFE&size=100' },
    codigoAtendimento: 'ATD-006',
    duracao: '10 min',
    comentarioProfissional: 'Coleta de sangue realizada com sucesso. Amostra enviada para análise.',
    documentosDisponiveis: getDocumentosDisponiveis('6'),
    valorAtendimento: 45.00,
    metodoPagamento: 'pix',
    parcelado: false,
    rescheduleStatus: 'bloqueado',
  },
  {
    id: '7',
    tipo: 'cuidado',
    titulo: 'Vacinação',
    profissional: 'Enf. Roberto Santos',
    especialidade: 'Enfermagem',
    data: '22/10/2024',
    hora: '14:00',
    local: 'Posto de Saúde Municipal',
    status: 'concluido',
    observacoes: 'Vacina contra gripe aplicada.',
    avatar: { uri: 'https://api.dicebear.com/7.x/avataaars/png?seed=RobertoSantos&backgroundColor=FD79A8&size=100' },
    codigoAtendimento: 'ATD-007',
    duracao: '5 min',
    comentarioProfissional: 'Vacinação contra influenza realizada sem intercorrências.',
    documentosDisponiveis: getDocumentosDisponiveis('7'),
    valorAtendimento: 25.00,
    metodoPagamento: 'dinheiro',
    parcelado: false,
    rescheduleStatus: 'disponivel',
  },
  {
    id: '8',
    tipo: 'consulta',
    titulo: 'Consulta Oftalmológica',
    profissional: 'Dr. Pedro Alves',
    especialidade: 'Oftalmologista',
    data: '18/10/2024',
    hora: '10:15',
    local: 'Clínica da Visão',
    status: 'concluido',
    observacoes: 'Exame de vista realizado. Prescrição atualizada.',
    avatar: { uri: 'https://api.dicebear.com/7.x/avataaars/png?seed=PedroAlves&backgroundColor=00B894&size=100' },
    codigoAtendimento: 'ATD-008',
    duracao: '35 min',
    comentarioProfissional: 'Exame oftalmológico completo realizado. Acuidade visual preservada.',
    comentarioAdicional: 'Paciente precisará de óculos para leitura.',
    documentosDisponiveis: getDocumentosDisponiveis('8'),
    valorAtendimento: 180.00,
    metodoPagamento: 'cartao_credito',
    numeroCartao: '5678',
    parcelado: true,
    numeroParcelas: 4,
    valorParcela: 45.00,
    rescheduleStatus: 'disponivel',
  },
  {
    id: '9',
    tipo: 'exame',
    titulo: 'Raio X do Tórax',
    profissional: 'Dra. Mariana Costa',
    especialidade: 'Radiologista',
    data: '15/10/2024',
    hora: '16:45',
    local: 'Centro Radiológico',
    status: 'concluido',
    observacoes: 'Raio X realizado. Laudo normal.',
    avatar: { uri: 'https://api.dicebear.com/7.x/avataaars/png?seed=MarianaCosta&backgroundColor=E17055&size=100' },
    codigoAtendimento: 'ATD-009',
    duracao: '20 min',
    comentarioProfissional: 'Exame radiológico do tórax realizado. Estruturas normais.',
    documentosDisponiveis: getDocumentosDisponiveis('9'),
    valorAtendimento: 90.00,
    metodoPagamento: 'pix',
    parcelado: false,
    rescheduleStatus: 'indisponivel',
  },
  {
    id: '10',
    tipo: 'consulta',
    titulo: 'Consulta Ginecológica',
    profissional: 'Dra. Laura Fernandes',
    especialidade: 'Ginecologista',
    data: '25/10/2024',
    hora: '13:30',
    local: 'Clínica Feminina',
    status: 'reagendado',
    observacoes: 'Consulta reagendada para próxima semana.',
    avatar: { uri: 'https://api.dicebear.com/7.x/avataaars/png?seed=LauraFernandes&backgroundColor=D63031&size=100' },
    codigoAtendimento: 'ATD-010',
    duracao: '50 min',
    comentarioProfissional: 'Consulta reagendada devido à indisponibilidade da paciente.',
    documentosDisponiveis: getDocumentosDisponiveis('10'),
    valorAtendimento: 160.00,
    metodoPagamento: 'cartao_credito',
    numeroCartao: '9012',
    parcelado: false,
    rescheduleStatus: 'expirado',
  },
  {
    id: '11',
    tipo: 'cuidado',
    titulo: 'Curativo',
    profissional: 'Enf. Juliana Rocha',
    especialidade: 'Enfermagem',
    data: '15/10/2024',
    hora: '08:30',
    local: 'Hospital Regional',
    status: 'concluido',
    observacoes: 'Curativo de ferida realizado.',
    avatar: { uri: 'https://api.dicebear.com/7.x/avataaars/png?seed=JulianaRocha&backgroundColor=6C5CE7&size=100' },
    codigoAtendimento: 'ATD-011',
    duracao: '15 min',
    comentarioProfissional: 'Curativo realizado com troca de material. Ferida em processo de cicatrização.',
    comentarioAdicional: 'Paciente orientado sobre cuidados domiciliares.',
    documentosDisponiveis: getDocumentosDisponiveis('11'),
    valorAtendimento: 40.00,
    metodoPagamento: 'dinheiro',
    parcelado: false,
    rescheduleStatus: 'disponivel',
  },
  {
    id: '12',
    tipo: 'consulta',
    titulo: 'Consulta Psicológica',
    profissional: 'Dr. André Silva',
    especialidade: 'Psicólogo',
    data: '23/10/2024',
    hora: '17:00',
    local: 'Centro de Saúde Mental',
    status: 'concluido',
    observacoes: 'Sessão de terapia realizada.',
    avatar: { uri: 'https://api.dicebear.com/7.x/avataaars/png?seed=AndreSilva&backgroundColor=FDCB6E&size=100' },
    codigoAtendimento: 'ATD-012',
    duracao: '55 min',
    comentarioProfissional: 'Sessão terapêutica focada em estratégias de coping e manejo do estresse.',
    comentarioAdicional: 'Paciente demonstrou engajamento no processo terapêutico.',
    documentosDisponiveis: getDocumentosDisponiveis('12'),
    valorAtendimento: 130.00,
    metodoPagamento: 'cartao_credito',
    numeroCartao: '3456',
    parcelado: true,
    numeroParcelas: 6,
    valorParcela: 21.67,
    rescheduleStatus: 'disponivel',
  }
];